[package]
name = "image2ascii"
version = "0.1.0"
edition = "2021"
authors = ["devanarayanj.mec@gmail.com"]

[dependencies]
image = "0.24.5"
anyhow = "1.0.66"
colored = "2.0.0"
clap = {version = "4.0.26", features = ["derive"]}

